### ISSUE TITLE
`shp buildrun list` crashes when a BuildRun status has no startTime

### ISSUE THREAD

**Issue by jerolimov** [shipwright-io/cli#114]
The cli crashes when listing all BuildRuns and one of them doesn't have a `status.startTime`. This could be reproduced when creating a BuildRun and linking a non-existing strategy.

Tested with Shipwright operator 0.9.0 and cli 0.9.0.

Example (with the status you get when running it):

```yaml
apiVersion: shipwright.io/v1alpha1
kind: BuildRun
metadata:
  name: missing-strategy
spec:
  buildSpec:
    output:
      image: 'foo/bar:latest'
    source:
      contextDir: source-build
      url: 'https://github.com/shipwright-io/sample-go.git'
    strategy:
      kind: ClusterBuildStrategy
      name: missing-strategy
status:
  completionTime: '2022-05-04T07:49:11Z'
  conditions:
    - lastTransitionTime: '2022-05-04T07:49:11Z'
      message: clusterBuildStrategy missing-strategy does not exist
      reason: BuildRegistrationFailed
      status: 'False'
      type: Succeeded
```

```
➜  ~ shp buildrun -n christoph list 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1789e33]

goroutine 1 [running]:
github.com/shipwright-io/cli/pkg/shp/cmd/buildrun.(*ListCommand).Run(0xc0002cbab0, 0xc0006bfd40, 0xc0006bfd68)
	github.com/shipwright-io/cli/pkg/shp/cmd/buildrun/list.go:88 +0x2d3
github.com/shipwright-io/cli/pkg/shp/cmd/runner.(*Runner).RunE(0xc0000ab080, 0xc0006bfd50, {0xc0000ab3e0, 0x0, 0x0})
	github.com/shipwright-io/cli/pkg/shp/cmd/runner/runner.go:35 +0x89
github.com/spf13/cobra.(*Command).execute(0xc0001a6f00, {0xc0000ab3c0, 0x2, 0x2})
	github.com/spf13/cobra@v1.4.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x2dad1e0)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	./main.go:43 +0xe5
```

Expect a null check is missing here:

https://github.com/shipwright-io/cli/blob/16b20d8757cff492aa0a89e60928c57decd075f5/pkg/shp/cmd/buildrun/list.go#L88
